spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:input
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create

#h2 console url = http://localhost:8080/h2-console